language: cpp

dist: trusty
sudo: false


compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
      - llvm-toolchain-trusty-3.9

    packages:
      - g++-6
      - gcc-6
      - clang-3.9
      - clang-format-3.9
      - cmake
      - cmake-data

install:
  - if [[ "$CXX" == "clang++" ]]; then export CXX=clang++-3.9; export CC=clang-3.9; fi
  - if [[ "$CXX" == "g++"     ]]; then export CXX=g++-6;       export CC=gcc-6;     fi
  - export CLANG_FORMAT_CMD=clang-format-3.9

script:
  - ./checkFormat.sh --only-check
  - mkdir build
  - cd build
  - cmake ..
  - make
