language: cpp

dist: trusty
sudo: required

services:
  - docker

compiler:
  - gcc
  - clang

install:
  - docker pull eplviz/archlinux_base
  - gem install coveralls-lcov

script:
  - docker run -p 127.0.0.1:80:4567 -t --name builder -v "$PWD":"$PWD" -w "$PWD" eplviz/archlinux_base ./travisRun.sh $CXX

after_success:
  - if [[ $CXX == "g++" ]]; then docker cp builder:coverage.info . ;                        fi
  - if [[ $CXX == "g++" ]]; then coveralls-lcov --source-encoding=ISO-8859-1 coverage.info; fi
