language: cpp

dist: trusty
sudo: required

services:
  - docker

compiler:
  - gcc
  - clang

install:
  - docker pull eplviz/archlinux_base
  - gem install coveralls-lcov

script:
  - docker run -t -i --name builder -v "${PWD}:${PWD}" -w "$PWD" eplviz/archlinux_base ./travisRun.sh $CXX

after_success:
  - docker cp builder:coverage.info .
  - coveralls-lcov --source-encoding=ISO-8859-1 coverage.info
